version: '3.5'

services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - mariadb_vol:/var/lib/mysql
      - ../../backups/${PROJECT_NAME}/mariadb:/backups
      - ../../system-services/extra/mariadb/actions:/actions
    expose:
      - '3306'
    networks:
      - internal
    environment:
      - "MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MARIADB_DATABASE}"
      - "MYSQL_USER=${MARIADB_USER}"
      - "MYSQL_PASSWORD=${MARIADB_PASSWORD}"
      - "USER_ID=${USER_ID}"
      - "GROUP_ID=${GROUP_ID}"

volumes:
  mariadb_vol:
