version: '3.5'

services:
  mysql:
    image: mariadb
    restart: always
    volumes:
      - db_vol:/var/lib/mysql
    expose:
      - '3306'
    networks:
      - internal
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"

# We keep db_vol for this volume for backward compatibility
volumes:
  db_vol:
