version: '3.5'

services:
  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    restart: always
    volumes:
      - mariadb_vol:/var/lib/mysql
      - ../../backups/${PROJECT_NAME}/mariadb:/backups
      - ../../system-services/extra/mariadb/actions:/actions
    expose:
      - '3306'
    networks:
      - internal
    environment:
      - "MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MARIADB_DATABASE}"
      - "MYSQL_USER=${MARIADB_USER}"
      - "MYSQL_PASSWORD=${MARIADB_PASSWORD}"
      - "USER_ID=${USER_ID}"
      - "GROUP_ID=${GROUP_ID}"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${MARIADB_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 20s
      retries: 10

  mariadb-backup:
    build:
      context: ../../system-services/extra/mariadb
      dockerfile: backup.Dockerfile
      args:
        - UID=${USER_ID}
        - GID=${GROUP_ID}
        - MARIADB_BACKUP_HOUR=${MARIADB_BACKUP_HOUR}
    environment:
      - "PROJECT=${PROJECT_NAME}"
    env_file:
      - ../../docker-data/${PROJECT_NAME}/.env
    depends_on:
      - mariadb
    networks:
      - internal
    volumes:
      - ../../backups/${PROJECT_NAME}/mariadb:/backups
    command: "crond -f -d 8"
    restart: always

volumes:
  mariadb_vol:
