version: '3.5'

services:
  postfix:
    image: boky/postfix
    restart: always
    volumes:
      - ../../docker-data/${PROJECT_NAME}/services/extra/postfix/keys:/etc/opendkim/keys
    expose:
      - "587"
    networks:
      - internal
    environment:
      - "HOSTNAME=${MAIL_HOST}"
      - "ALLOWED_SENDER_DOMAINS=${MAIL_HOST} ${MAIL_HOST_ALIASES}"
