version: '3.5'

services:
  ghost:
    image: ghost:${GHOST_VERSION:-alpine}
    restart: always
    volumes:
      - ../../instance-data/${PROJECT_NAME}/ghost-content:/var/lib/ghost/content
      - ../../instance-data/${PROJECT_NAME}/ghost-logs:/var/log/ghost
    expose:
      - 2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      - "mail__from=${GHOST_EMAIL}"
      - "NODE_ENV=production"
      - "url=https://${WEB_HOST}"
    networks:
      - proxy
    labels:
      - "traefik.enable=${PROXY_TMP_ENABLED}"
      - "traefik.port=2368"
      - "traefik.frontend.rule=Host:${PROXY_TMP_FE_HOST}"
      - "traefik.frontend.auth.basic.users=${WEB_AUTH_BASIC}"
      - "traefik.frontend.priority=${PROXY_TMP_PRIORITY}"
      - "traefik.frontend.redirect.regex=^https?://(${PROXY_TMP_REGEX_REDIRECT})/(.*)"
      - "traefik.frontend.redirect.replacement=https://${WEB_HOST}/$${2}"
      - "traefik.frontend.redirect.permanent=true"
