version: '3.5'

services:
  ghost:
    image: ghost:${GHOST_VERSION:-alpine}
    restart: always
    volumes:
      - ../../instance-data/${PROJECT_NAME}/${WEB_ROOT_DOCKER_HOST}:/var/lib/ghost/content
      - ../../logs/${PROJECT_NAME}/ghost:/var/log/ghost
#    command: tail -f /dev/null
    expose:
      - 2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      - "database__client=mysql"
      - "database__connection__host=mysql"
      - "database__connection__user=${MYSQL_USER}"
      - "database__connection__password=${MYSQL_PASSWORD}"
      - "database__connection__database=${MYSQL_DATABASE}"
      - "mail__from=${GHOST_EMAIL}"
      - "NODE_ENV=production"
      - "url=https://${WEB_HOST}"
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=${PROXY_TMP_ENABLED}"
      - "traefik.port=2368"
      - "traefik.frontend.rule=Host:${PROXY_TMP_FE_HOST}"
      - "traefik.frontend.auth.basic.users=${WEB_AUTH_BASIC}"
      - "traefik.frontend.priority=${PROXY_TMP_PRIORITY}"
      - "traefik.frontend.redirect.regex=^https?://(${PROXY_TMP_REGEX_REDIRECT})/(.*)"
      - "traefik.frontend.redirect.replacement=https://${WEB_HOST}/$${2}"
      - "traefik.frontend.redirect.permanent=true"
