version: '3.5'

services:
  webserver:
    build:
      context: ../../docker-data/${PROJECT_NAME}/services/main/webserver
      # Dockerfile will be built by scripts.sh->build() when running compose.sh
      dockerfile: "generated.Dockerfile"
      args:
        - "PHP_VERSION=${PHP_VERSION}-apache"
        - "PHP_EXTENSIONS=${PHP_EXTENSIONS}"
        - "APACHE_MODULES=${APACHE_MODULES}"
        - "APT_LIBS=${APT_LIBS}"
        - "UID=${USER_ID}"
        - "GID=${GROUP_ID}"
    restart: always
    expose:
      - '80'
    volumes:
      - ../../instance-data/${PROJECT_NAME}/${WEB_ROOT_DOCKER_HOST}:/var/www/html
      - ../../logs/${PROJECT_NAME}/webserver:/var/log/apache2
    env_file:
      - ../../docker-data/${PROJECT_NAME}/.env
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=${PROXY_TMP_ENABLED}"
      - "traefik.frontend.rule=Host:${PROXY_TMP_FE_HOST}"
      - "traefik.frontend.auth.basic.users=${WEB_AUTH_BASIC}"
      - "traefik.frontend.priority=${PROXY_TMP_PRIORITY}"
      - "traefik.port=80"
      - "traefik.frontend.redirect.regex=^https?://(${PROXY_TMP_REGEX_REDIRECT})/(.*)"
      - "traefik.frontend.redirect.replacement=https://${WEB_HOST}/$${2}"
      - "traefik.frontend.redirect.permanent=true"
    healthcheck:
      test: "curl --fail http://localhost || exit 1"
      interval: 5s
      timeout: 20s
      retries: 10
