version: '3.5'
services:
  geoip:
    image: maxmindinc/geoipupdate
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168 # update every 7 days
      - GEOIPUPDATE_ACCOUNT_ID=${GEOIP_ACCOUNT_ID}
      - GEOIPUPDATE_LICENSE_KEY=${GEOIP_LICENSE_KEY}
    volumes:
      - geoip:/usr/share/GeoIP
    networks:
      - internal

volumes:
  geoip:
