version: '3.5'

services:
  nextcloud:
    build:
      context: ../../system-services/main/nextcloud
      dockerfile: "Dockerfile"
      args:
        - NEXTCLOUD_VERSION=${NEXTCLOUD_VERSION}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    restart: always
    volumes:
      - ../../instance-data/${PROJECT_NAME}/${WEB_ROOT_DOCKER_HOST}:/var/www/html/data
      - config:/var/www/html/config
      - apps:/var/www/html/apps
    expose:
      - 80
    env_file:
      - ../../docker-data/${PROJECT_NAME}/.env
    environment:
      - "REDIS_HOST=redis"
      - "MYSQL_HOST=mariadb"
      - "NEXTCLOUD_TRUSTED_DOMAINS=${WEB_HOST} ${WEB_HOST_ALIASES}"
    depends_on:
      - mariadb
      - redis
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=${PROXY_TMP_ENABLED}"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${PROXY_TMP_FE_HOST}"
      - "traefik.frontend.auth.basic.users=${WEB_AUTH_BASIC}"
      - "traefik.frontend.priority=${PROXY_TMP_PRIORITY}"
      - "traefik.frontend.redirect.regex=^https?://(${PROXY_TMP_REGEX_REDIRECT})/(.*)"
      - "traefik.frontend.redirect.replacement=https://${WEB_HOST}/$${2}"
      - "traefik.frontend.redirect.permanent=true"

volumes:
  config:
  apps:
