version: '3.5'

services:
  app: &nextcloudConfig
    build:
      context: ../../system-services/main/nextcloud
      dockerfile: "app.Dockerfile"
      args:
        - NEXTCLOUD_VERSION=${NEXTCLOUD_VERSION}
        - UID=${USER_ID}
        - GID=${GROUP_ID}
    restart: always
    networks:
      - internal
    volumes:
      - ../../instance-data/${PROJECT_NAME}/${WEB_ROOT_DOCKER_HOST}:/var/www/html/data
      - nextcloud:/var/www/html
    env_file:
      - ../../docker-data/${PROJECT_NAME}/.env
    environment:
      - "REDIS_HOST=redis"
      - "MYSQL_HOST=mariadb"
      - "MYSQL_USER=${MARIADB_USER}"
      - "MYSQL_PASSWORD=${MARIADB_PASSWORD}"
      - "MYSQL_DATABASE=${MARIADB_DATABASE}"
      - "NEXTCLOUD_TRUSTED_DOMAINS=${WEB_HOST} ${WEB_HOST_ALIASES}"
      - "SMTP_HOST=postfix"
      - "SMTP_PORT=587"
      - "SMTP_AUTHTYPE="
      - "MAIL_FROM_ADDRESS=${NEXTCLOUD_EMAIL_SENDER}"
      - "TRUSTED_PROXIES=traefik"
      - "PHP_MEMORY_LIMIT=${NEXTCLOUD_PHP_MEMORY_LIMIT:-512M}"
    depends_on:
      - mariadb
      - redis
      - postfix

  cron:
    <<: *nextcloudConfig
    entrypoint: "/cron.sh"
    command: ""

  nginx:
    build:
      context: ../../system-services/main/nextcloud
      dockerfile: "nginx.Dockerfile"
      args:
        - UID=${USER_ID}
        - GID=${GROUP_ID}
    volumes:
      - ../../system-services/main/nextcloud/nginx.conf:/etc/nginx/nginx.conf.template:ro
      - nextcloud:/var/www/html:ro
    restart: always
    environment:
      - "WEB_HOST=${WEB_HOST}"
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=${PROXY_TMP_ENABLED}"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${PROXY_TMP_FE_HOST}"
      - "traefik.frontend.auth.basic.users=${WEB_AUTH_BASIC}"
      - "traefik.frontend.priority=${PROXY_TMP_PRIORITY}"
      - "traefik.frontend.redirect.regex=^https?://(${PROXY_TMP_REGEX_REDIRECT})/(.*)"
      - "traefik.frontend.redirect.replacement=https://${WEB_HOST}/$${2}"
      - "traefik.frontend.redirect.permanent=true"
    depends_on:
      - app

volumes:
  nextcloud: