version: '3.5'

services:
  nextcloud:
    image: nextcloud:production-apache
    restart: always
    volumes:
      - ../../instance-data/${PROJECT_NAME}/${WEB_ROOT_DOCKER_HOST}:/var/www/html/data
      - config:/var/www/html/config
      - apps:/var/www/html/apps
    expose:
      - 80
    environment:
      - "REDIS_HOST=redis"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_HOST=mysql"
    depends_on:
      - mysql
      - redis
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=${PROXY_TMP_DISABLED}"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${PROXY_TMP_FE_HOST}"
      - "traefik.frontend.auth.basic.users=${WEB_AUTH_BASIC}"
      - "traefik.frontend.priority=${PROXY_TMP_PRIORITY}"
      - "traefik.frontend.redirect.regex=^https?://(${PROXY_TMP_REGEX_REDIRECT})/(.*)"
      - "traefik.frontend.redirect.replacement=https://${WEB_HOST}/$${2}"
      - "traefik.frontend.redirect.permanent=true"

  nextcloud_cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ../../instance-data/${PROJECT_NAME}/${WEB_ROOT_DOCKER_HOST}:/var/www/html/data
      - config:/var/www/html/config
      - apps:/var/www/html/apps
    entrypoint: /cron.sh
    networks:
      - internal
    depends_on:
      - mysql
      - redis

volumes:
  config:
  apps:
