version: '3.5'

services:
  dropbox:
    build:
      context: ../../system-services/main/dropbox
      dockerfile: "Dockerfile"
      args:
        - DROPBOX_LOCALE=${DROPBOX_LOCALE}
        - UID=${USER_ID}
        - GID=${GROUP_ID}
    restart: always
    volumes:
      - ../../instance-data/${PROJECT_NAME}/${WEB_ROOT_DOCKER_HOST}:/home/dropbox/Dropbox
      - dropbox_data:/home/dropbox/.dropbox
    networks:
      - internal
    #entrypoint: tail -f /dev/null

volumes:
  dropbox_data:
