version: '3.5'

services:
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION:-latest}
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    networks:
      - proxy
      - internal
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${PGADMIN_WEB_HOST}"
      - "traefik.frontend.auth.basic.users=${PGADMIN_WEB_AUTH_BASIC}"
      - "traefik.port=80"
    links:
      - postgresql

volumes:
  pgdata: