version: '3.5'
services:
  traefik:
    image: traefik:${TRAEFIK_VERSION:-alpine}
    command: '--acme.email=${TRAEFIK_ADMIN_EMAIL}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../system/services/reverse-proxy/traefik.toml:/traefik.toml
      - ../../system/configuration/acme.json:/acme.json
    restart: always
    networks:
      - traefik-proxy
      - sys-internal
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.frontend.rule=Host:${TRAEFIK_WEB_HOST}"
      - "traefik.frontend.auth.basic.users=${TRAEFIK_WEB_AUTH_BASIC}"
      - "traefik.enable=${TRAEFIK_WEB_ENABLED}"
      - "traefik.port=8080"

networks:
  traefik-proxy:
    name: traefik-proxy
