version: '3.5'

services:
  jobs:
    build:
      context: data
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    networks:
      - internal
    environment:
      - "MYSQL_HOST=mysql"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "KEEP_BACKUP_DAYS=${KEEP_BACKUP_DAYS}"
      - "PROJECT=${PROJECT_NAME}"
    volumes:
      - ../../../backups/${PROJECT_NAME}:/home/backup
      - ../../../cronjobs/${PROJECT_NAME}:/cronjobs
    command: "crond -f -d 8"
    restart: always
