version: '3.5'

services:
  jobs:
    build:
      context: ../../system-services/extra/jobs/data
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    networks:
      - internal
    environment:
      - "PROJECT=${PROJECT_NAME}"
    volumes:
      - ../../cronjobs/${PROJECT_NAME}:/cronjobs
    command: "crond -f -d 8"
    restart: always
